server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 60

spring:
  profiles:
    active: data
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:/templates/
    check-template: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
    cache: false



























